version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
      POSTGRES_DB: shopdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: shop
  #     POSTGRES_PASSWORD: shop
  #     POSTGRES_DB: shopdb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   command:
  #     - "postgres"
  #     - "-c"
  #     - "shared_buffers=2MB"
  #     - "-c"
  #     - "autovacuum_vacuum_insert_threshold=1"
  #     - "-c"
  #     - "autovacuum_vacuum_threshold=0"
  #     - "-c"
  #     - "autovacuum_vacuum_scale_factor=0"
  #     - "-c"
  #     - "autovacuum_naptime=1"
  #     - "-c"
  #     - "vacuum_cost_limit=10000"
  #     - "-c"
  #     - "vacuum_cost_page_dirty=0"
  #     - "-c"
  #     - "vacuum_cost_page_hit=0"
  #     - "-c"
  #     - "vacuum_cost_page_miss=0"
  #     - "-c"
  #     - "autovacuum_analyze_threshold=0"
  #     - "-c"
  #     - "autovacuum_analyze_scale_factor=0"
  #     - "-c"
  #     - "log_autovacuum_min_duration=0"
  #     - "-c"
  #     - "logging_collector=on"
  #     - "-c"
  #     - "log_destination=stderr"
  #     - "-c"
  #     - "random_page_cost=1000000"
  #     - "-c"
  #     - "cpu_index_tuple_cost=1000000"
  #     - "-c"
  #     - "effective_cache_size=1MB"
  #     - "-c"
  #     - "checkpoint_timeout=30s"
  #     - "-c"
  #     - "max_wal_size=32MB"
  #     - "-c"
  #     - "wal_writer_delay=1"
  #     - "-c"
  #     - "track_wal_io_timing=on"
  #     - "-c"
  #     - "log_statement=all"
  #     - "-c"
  #     - "max_parallel_workers_per_gather=0"


  db_test:
    image: postgres:15
    environment:
      POSTGRES_USER: testshop
      POSTGRES_PASSWORD: testshop
      POSTGRES_DB: testshopdb
    ports:
      - "5433:5432"
    profiles: ["test"]

  app:
    build: .
    depends_on:
      - db
      - tempo
    environment:
      DATABASE_URL: postgresql://shop:shop@db:5432/shopdb
      EXTERNAL_SERVICE_URL: http://external_service:8001
      EXTERNAL_SERVICE_HTTP2_URL: https://external_service:8443
      EXT_CLIENT_CONNECT_TIMEOUT: 2
      EXT_CLIENT_READ_TIMEOUT: 180
      EXT_CLIENT_WRITE_TIMEOUT: 5
      EXT_CLIENT_POOL_TIMEOUT: 0.05
      EXT_CLIENT_MAX_CONNECTIONS: 100
      EXT_CLIENT_MAX_KEEPALIVE_CONNECTIONS: 20
      EXT_CLIENT_KEEPALIVE_EXPIRY: 5
      EXT_CLIENT_HTTP2_ENABLED: "true"
      EXT_CLIENT_CA_CERT: /app/certs/local_ca.crt
    volumes:
      - ./:/app      
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  pgadmin:
    image: dpage/pgadmin4
    container_name: shop-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
  
  external_service:
    build: ./external_service
    container_name: external_service
    ports:
      - "8001:8001"
      - "8443:8443"
    depends_on:
      - db
      - tempo
    environment:
      EXTERNAL_DELAY_MIN_SECONDS: 0
      EXTERNAL_DELAY_MAX_SECONDS: 0

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://shop:shop@db:5432/shopdb?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--enable-feature=remote-write-receiver"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=native-histograms"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./monitoring/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"   # Tempo UI
      - "4317:4317"   # gRPC
      - "4318:4318"

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: ["-config.file=/etc/promtail/config.yml"]
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
      - tempo
      - loki
      - promtail
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/provisioning:/etc/grafana/provisioning
      - ./monitoring/dashboards:/etc/grafana/dashboards

volumes:
  db_data:
